server:
  port: 9393
spring:
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/lucker?currentSchema=dataflow
    username: postgres
    password: postgres